### PR TITLE
Switch from puppeteer to playwright

### PR DESCRIPTION
**Pull request by nicholasray**
Playwright offers much better support for auto-waiting [1] and IMO less test flakiness which should make writing and maintaining visual tests easier. In addition, by running backstop/playwright on the host machine, we can simplify or remove a lot of the code.

* Removes visual regression docker container in favor of running backstop on host machine
* Removes a lot of code and complexity that was needed for the docker container
* Fixes periodic freezing issue on MacBook Pro M1 and lack of chromium support

[1] https://playwright.dev/docs/actionability

Bug: T318445

### CODE REVIEW

**Comment by nicholasray** [comment]
Will test this a bit more

**Comment by nicholasray** [comment]
Remaining work on this includes adding a replacement for waitForNetworkIdle which works differently in playwright vs. puppeteer. This is needed, for example, to prevent image not being fully loaded:

**Comment by nicholasray** [comment]
The search tests should be reviewed too because I believe we use no-js logic in puppeteer that playwright may not support

**Comment by montehurd** [comment]
closing for now

keeping docker containment since arm64 chromium issue has been addressed

**Pull request closed without merging**
