### PR TITLE
Add ability to log a11y results to graphite, and add a11y tests to the `runAll` command

### PR DESCRIPTION
**Pull request by bernardwang**
Now the `-l` or `--logResults` option will send a11y test data to graphite to be used in grafana

### CODE REVIEW

**Comment by jdlrobson** [comment]
Hey @bernardwang I'm getting the following error when I run `./pixel.js reference -g desktop-a11y && ./pixel.js test -g desktop-a11y`:

```
Error: Cannot find module '/pixel/configDesktopA11y.js'
Require stack:
- /usr/local/lib/node_modules/backstopjs/core/util/makeConfig.js
- /usr/local/lib/node_modules/backstopjs/core/runner.js
- /usr/local/lib/node_modules/backstopjs/cli/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at loadProjectConfig (/usr/local/lib/node_modules/backstopjs/core/util/makeConfig.js:44:36)
    at makeConfig (/usr/local/lib/node_modules/backstopjs/core/util/makeConfig.js:62:40)
    at module.exports (/usr/local/lib/node_modules/backstopjs/core/runner.js:5:18)
    at main (/usr/local/lib/node_modules/backstopjs/cli/index.js:40:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/backstopjs/cli/index.js:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/backstopjs/core/util/makeConfig.js',
    '/usr/local/lib/node_modules/backstopjs/core/runner.js',
    '/usr/local/lib/node_modules/backstopjs/cli/index.js'
  ]
```

**Comment by bernardwang** [comment]
> Hey @bernardwang I'm getting the following error when I run `./pixel.js reference -g desktop-a11y && ./pixel.js test -g desktop-a11y`:

Ah, so the usage for a11y tests is to add the -a or --a11y flag to the command, i.e. 
`./pixel.js reference -a -g desktop && ./pixel.js test -a -g desktop` or 
`./pixel.js reference -a -g mobile && ./pixel.js test -a -g mobile`

**Review by jdlrobson — CHANGES_REQUESTED** [review]
[] Please update README with the new commands
[] Throw a human-friendly error when the group is used incorrectly or doesn't exist e.g. `./pixel.js test -a -g web-maintained` and `./pixel.js reference -g desktop-a11y` and `./pixel.js test -g desktop-a11y`

**Comment by bernardwang** [comment]
> [] Please update README with the new commands [] Throw a human-friendly error when the group is used incorrectly or doesn't exist e.g. `./pixel.js test -a -g web-maintained` and `./pixel.js reference -g desktop-a11y` and `./pixel.js test -g desktop-a11y`

Ok these should be done! The command were already documented in the README under "Accessibility regression testing", lmk if theres anything i missed. 

The error was being thrown, but not being logged to console which is weird

**Comment by jdlrobson** [comment]
Thanks for your patience on this one! Reviewing now!

**Review by jdlrobson — APPROVED** [review]

**Pull request merged**
