### PR TITLE
Use specific Chromium arm binary

### PR DESCRIPTION
**Pull request by montehurd**
Closer to version expected by version of Puppeteer used by BackstopJS

Bug: T332353

### CODE REVIEW

**Comment by nicholasray** [comment]
Thank you for putting this in a PR. I'm not sure if this is a transient issue, but I'm getting the following `503: Backend fetch failed` error when trying to build the new image. Is this image building for you after you run `./pixel.js clean; ./pixel.js reference`?

```
 > [pixel-visual-regression 3/7] RUN /bin/bash -c 'set -ex &&     ARCH=`uname -m` &&     if [ "$ARCH" == "x86_64" ]; then        sudo npm install -g --unsafe-perm=true --allow-root backstopjs@${BACKSTOPJS_VERSION};     else        sudo PUPPETEER_SKIP_DOWNLOAD=true PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm install -g --unsafe-perm=true --allow-root backstopjs@${BACKSTOPJS_VERSION} &&        wget "${CHROMIUM_ARM_URL}${CHROMIUM_ARM_COMMON_BINARY}"             "${CHROMIUM_ARM_URL}${CHROMIUM_ARM_BINARY}" &&        apt install -y "./${CHROMIUM_ARM_COMMON_BINARY}"                       "./${CHROMIUM_ARM_BINARY}" &&        sudo test -f /usr/bin/chromium && sudo ln -s /usr/bin/chromium /usr/bin/chromium-browser && sudo ln -s /usr/bin/chromium /usr/bin/chrome;     fi':                    
#0 0.159 ++ uname -m                                                                                                                                                                                                                                                   
#0 0.161 + ARCH=aarch64                                                                                                                                                                                                                                                
#0 0.161 + '[' aarch64 == x86_64 ']'
#0 0.161 + sudo PUPPETEER_SKIP_DOWNLOAD=true PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm install -g --unsafe-perm=true --allow-root backstopjs@6.1.1
#0 0.484 npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
#0 9.008 npm WARN deprecated puppeteer@15.5.0: < 19.4.0 is no longer supported
#0 402.0 
#0 402.0 added 173 packages, and audited 174 packages in 7m
#0 402.0 
#0 402.0 19 packages are looking for funding
#0 402.0   run `npm fund` for details
#0 402.0 
#0 402.0 found 0 vulnerabilities
#0 402.0 npm notice 
#0 402.0 npm notice New major version of npm available! 8.11.0 -> 9.6.4
#0 402.0 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.4>
#0 402.0 npm notice Run `npm install -g npm@9.6.4` to update!
#0 402.0 npm notice 
#0 402.0 + wget http://snapshot.debian.org/archive/debian-security/20220902T180902Z/pool/updates/main/c/chromium/chromium-common_105.0.5195.52-1~deb11u1_arm64.deb http://snapshot.debian.org/archive/debian-security/20220902T180902Z/pool/updates/main/c/chromium/chromium_105.0.5195.52-1~deb11u1_arm64.deb
#0 402.0 --2023-04-06 00:07:05--  http://snapshot.debian.org/archive/debian-security/20220902T180902Z/pool/updates/main/c/chromium/chromium-common_105.0.5195.52-1~deb11u1_arm64.deb
#0 402.0 Resolving snapshot.debian.org (snapshot.debian.org)... 193.62.202.27, 185.17.185.185, 2001:1af8:4020:b030:deb::185, ...
#0 402.1 Connecting to snapshot.debian.org (snapshot.debian.org)|193.62.202.27|:80... connected.
#0 402.2 HTTP request sent, awaiting response... 503 Backend fetch failed
#0 462.4 2023-04-06 00:08:05 ERROR 503: Backend fetch failed.
#0 462.4 
#0 462.4 --2023-04-06 00:08:05--  http://snapshot.debian.org/archive/debian-security/20220902T180902Z/pool/updates/main/c/chromium/chromium_105.0.5195.52-1~deb11u1_arm64.deb
#0 462.4 Connecting to snapshot.debian.org (snapshot.debian.org)|193.62.202.27|:80... connected.
#0 462.5 HTTP request sent, awaiting response... 503 Backend fetch failed
#0 522.7 2023-04-06 00:09:06 ERROR 503: Backend fetch failed.
#0 522.7 
------
failed to solve: executor failed running [/bin/sh -c /bin/bash -c 'set -ex &&     ARCH=`uname -m` &&     if [ "$ARCH" == "x86_64" ]; then        sudo npm install -g --unsafe-perm=true --allow-root backstopjs@${BACKSTOPJS_VERSION};     else        sudo PUPPETEER_SKIP_DOWNLOAD=true PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm install -g --unsafe-perm=true --allow-root backstopjs@${BACKSTOPJS_VERSION} &&        wget "${CHROMIUM_ARM_URL}${CHROMIUM_ARM_COMMON_BINARY}"             "${CHROMIUM_ARM_URL}${CHROMIUM_ARM_BINARY}" &&        apt install -y "./${CHROMIUM_ARM_COMMON_BINARY}"                       "./${CHROMIUM_ARM_BINARY}" &&        sudo test -f /usr/bin/chromium && sudo ln -s /usr/bin/chromium /usr/bin/chromium-browser && sudo ln -s /usr/bin/chromium /usr/bin/chrome;     fi']: exit code: 8
Error: Exit with error code 17
    at ChildProcess.<anonymous> (/Users/nray/Development/pixel/src/BatchSpawn.js:104:13)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

**Comment by nicholasray** [comment]
After `./pixel.js clean; docker system prune -a; pixel.js reference`, there seems to be some kind of infinite loop happening:

https://user-images.githubusercontent.com/3496279/230244747-495f5800-1740-469c-ad24-27590cbaca25.mp4

**Comment by montehurd** [comment]
Yeah I just updated Docker and now I'm seeing the same thing... looking into it...

**Comment by montehurd** [comment]
Just tried it with a stripped down version. Seemed to work

Then tried with main branch and I'm seeing the same looping weirdness

**Comment by montehurd** [comment]
Here's stripped down version which seemed to work:

```
FROM node:16.15.1-bullseye

RUN apt-get update && \
    apt-get install -y curl xz-utils ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

# find links to chromium arm64 binaries here:
# 	http://snapshot.debian.org/binary/chromium/
ENV CHROMIUM_ARM_URL http://snapshot.debian.org/archive/debian-security/20220902T180902Z/pool/updates/main/c/chromium/
ENV CHROMIUM_ARM_BINARY chromium_105.0.5195.52-1~deb11u1_arm64.deb
ENV CHROMIUM_ARM_COMMON_BINARY chromium-common_105.0.5195.52-1~deb11u1_arm64.deb

RUN apt-get update && \
       wget "${CHROMIUM_ARM_URL}${CHROMIUM_ARM_COMMON_BINARY}" \
            "${CHROMIUM_ARM_URL}${CHROMIUM_ARM_BINARY}" && \
       apt install -y "./${CHROMIUM_ARM_COMMON_BINARY}" \
                      "./${CHROMIUM_ARM_BINARY}"

ENTRYPOINT ["tail", "-f", "/dev/null"]

```

**Comment by montehurd** [comment]
I see MacOS has an available update... going to try that and see if it helps 🤞

**Comment by montehurd** [comment]
Still seeing the issue, but starting to think it may be related to the setup /src/setupRepos.js script...

**Comment by montehurd** [comment]
ok both main and this branch started working again... weird

**Comment by montehurd** [comment]
@nicholasray 

i tried this to build the images without the seizure inducing flickering:

```
#!/bin/bash
services=$(docker-compose config --services)
for service in $services; do
  docker-compose build --progress=plain $service
done
```

on my end it looks like it pauses for a bit at setupRepos.js, but i don't see any other obvious issues 🤔

**Comment by nicholasray** [comment]
@montehurd Thank you for looking into this! I'm very interested in resolving these long-standing bugs on arm64 so great work in resolving those. 

I'm also interested in continuing to discuss with you a path where we can make the visual regression docker container optional for those who don't want to deal with the complexity involved in adding tests, debugging tests, etc. I've also filed https://phabricator.wikimedia.org/T334307 for the flickering, but I think it may be related to the latest docker version as I've never seen it before.

**Pull request merged**
